name: mongo-sharding

services:
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
    restart: always
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"

  configSrv:
    container_name: configSrv
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-config-data:/data/db
    command:
      [
        "--configsvr",
        "--replSet=config_server",
        "--bind_ip_all",
        "--port=27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1:
    container_name: shard1
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-shard1-data:/data/db
    ports:
      - 27018:27018
    command:
      [
        "--shardsvr",
        "--replSet=shard1",
        "--bind_ip_all",
        "--port=27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2:
    container_name: shard2
    image: mongo:latest
    restart: always
    volumes:
      - mongodb-shard2-data:/data/db
    ports:
      - 27019:27019
    command:
      [
        "--shardsvr",
        "--replSet=shard2",
        "--bind_ip_all",
        "--port=27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongos_router:
    container_name: mongos_router
    image: mongo:latest
    restart: always
    ports:
      - 27020:27020
    command: 
      [
        "mongos",
        "--configdb=config_server/configSrv:27017",
        "--bind_ip_all",
        "--port=27020"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

volumes:
  mongodb-config-data:
  mongodb-shard1-data:
  mongodb-shard2-data:
