name: mongo-sharding

services:

  # Приложение
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
    restart: always
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router"
      MONGODB_DATABASE_NAME: "somedb"

  # Роутер mongos
  mongos_router:
    container_name: mongos_router
    image: dh-mirror.gitverse.ru/mongo:latest
    depends_on: ["configSrv", "shard1", "shard2"]
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb-router-data:/data/db
    command: [ "mongos", "--configdb", "config_server/configSrv:27019", "--bind_ip_all", ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # Конфигурационный сервер
  configSrv:
    restart: always
    container_name: configSrv
    image: dh-mirror.gitverse.ru/mongo:latest
    volumes:
      - mongodb-config-data:/data/db
    command: [ "--configsvr", "--replSet", "config_server", "--bind_ip_all"] 
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27019" ]
      interval: 5s
      start_period: 10s

  # Шард 1
  shard1:
    container_name: shard1
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    volumes:
      - mongodb-shard1-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard1", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018" ]
      interval: 5s
      start_period: 10s

  # Шард 2
  shard2:
    container_name: shard2
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    volumes:
      - mongodb-shard2-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard2", "--bind_ip_all" ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018" ]
      interval: 5s
      start_period: 10s

volumes:
  mongodb-router-data:
  mongodb-config-data:
  mongodb-shard1-data:
  mongodb-shard2-data: